// WARNING: This header was generated by scripts/generate.py! Do not edit!

#pragma once

#include "terminal.h"
#include "ekUtil.h"

struct EL1001_t FINAL : terminal_t {
	static const uint32_t ID = 1001;
	static const uint16_t NUM_INPUTS = 1;
	static const uint16_t INPUT_SIZE = 1;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL1001_t() {
		str = "EL1001";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
};

struct EL1002_t FINAL : terminal_t {
	static const uint32_t ID = 1002;
	static const uint16_t NUM_INPUTS = 2;
	static const uint16_t INPUT_SIZE = 2;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL1002_t() {
		str = "EL1002";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
};

struct EL1004_t FINAL : terminal_t {
	static const uint32_t ID = 1004;
	static const uint16_t NUM_INPUTS = 4;
	static const uint16_t INPUT_SIZE = 4;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL1004_t() {
		str = "EL1004";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
};

struct EL1008_t FINAL : terminal_t {
	static const uint32_t ID = 1008;
	static const uint16_t NUM_INPUTS = 8;
	static const uint16_t INPUT_SIZE = 8;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL1008_t() {
		str = "EL1008";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
};

struct EL1012_t FINAL : terminal_t {
	static const uint32_t ID = 1012;
	static const uint16_t NUM_INPUTS = 2;
	static const uint16_t INPUT_SIZE = 2;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL1012_t() {
		str = "EL1012";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
};

struct EL1014_t FINAL : terminal_t {
	static const uint32_t ID = 1014;
	static const uint16_t NUM_INPUTS = 4;
	static const uint16_t INPUT_SIZE = 4;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL1014_t() {
		str = "EL1014";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
};

struct EL1018_t FINAL : terminal_t {
	static const uint32_t ID = 1018;
	static const uint16_t NUM_INPUTS = 8;
	static const uint16_t INPUT_SIZE = 8;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL1018_t() {
		str = "EL1018";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
};

struct EL1024_t FINAL : terminal_t {
	static const uint32_t ID = 1024;
	static const uint16_t NUM_INPUTS = 4;
	static const uint16_t INPUT_SIZE = 4;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL1024_t() {
		str = "EL1024";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
};

struct EL1034_t FINAL : terminal_t {
	static const uint32_t ID = 1034;
	static const uint16_t NUM_INPUTS = 4;
	static const uint16_t INPUT_SIZE = 4;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL1034_t() {
		str = "EL1034";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
};

struct EL1084_t FINAL : terminal_t {
	static const uint32_t ID = 1084;
	static const uint16_t NUM_INPUTS = 4;
	static const uint16_t INPUT_SIZE = 4;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL1084_t() {
		str = "EL1084";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
};

struct EL1088_t FINAL : terminal_t {
	static const uint32_t ID = 1088;
	static const uint16_t NUM_INPUTS = 8;
	static const uint16_t INPUT_SIZE = 8;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL1088_t() {
		str = "EL1088";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
};

struct EL1094_t FINAL : terminal_t {
	static const uint32_t ID = 1094;
	static const uint16_t NUM_INPUTS = 4;
	static const uint16_t INPUT_SIZE = 4;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL1094_t() {
		str = "EL1094";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
};

struct EL1098_t FINAL : terminal_t {
	static const uint32_t ID = 1098;
	static const uint16_t NUM_INPUTS = 8;
	static const uint16_t INPUT_SIZE = 8;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL1098_t() {
		str = "EL1098";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
};

struct EL1104_t FINAL : terminal_t {
	static const uint32_t ID = 1104;
	static const uint16_t NUM_INPUTS = 4;
	static const uint16_t INPUT_SIZE = 4;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL1104_t() {
		str = "EL1104";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
};

struct EL1114_t FINAL : terminal_t {
	static const uint32_t ID = 1114;
	static const uint16_t NUM_INPUTS = 4;
	static const uint16_t INPUT_SIZE = 4;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL1114_t() {
		str = "EL1114";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
};

struct EL1124_t FINAL : terminal_t {
	static const uint32_t ID = 1124;
	static const uint16_t NUM_INPUTS = 4;
	static const uint16_t INPUT_SIZE = 4;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL1124_t() {
		str = "EL1124";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
};

struct EL1134_t FINAL : terminal_t {
	static const uint32_t ID = 1134;
	static const uint16_t NUM_INPUTS = 4;
	static const uint16_t INPUT_SIZE = 4;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL1134_t() {
		str = "EL1134";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
};

struct EL1144_t FINAL : terminal_t {
	static const uint32_t ID = 1144;
	static const uint16_t NUM_INPUTS = 4;
	static const uint16_t INPUT_SIZE = 4;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL1144_t() {
		str = "EL1144";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
};

struct EL1184_t FINAL : terminal_t {
	static const uint32_t ID = 1184;
	static const uint16_t NUM_INPUTS = 4;
	static const uint16_t INPUT_SIZE = 4;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL1184_t() {
		str = "EL1184";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
};

struct EL1202_t FINAL : terminal_t {
	static const uint32_t ID = 1202;
	static const uint16_t NUM_INPUTS = 2;
	static const uint16_t INPUT_SIZE = 2;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL1202_t() {
		str = "EL1202";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
};

struct EL1382_t FINAL : terminal_t {
	static const uint32_t ID = 1382;
	static const uint16_t NUM_INPUTS = 2;
	static const uint16_t INPUT_SIZE = 2;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL1382_t() {
		str = "EL1382";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
};

struct EL1702_t FINAL : terminal_t {
	static const uint32_t ID = 1702;
	static const uint16_t NUM_INPUTS = 2;
	static const uint16_t INPUT_SIZE = 2;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL1702_t() {
		str = "EL1702";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
};

struct EL1712_t FINAL : terminal_t {
	static const uint32_t ID = 1712;
	static const uint16_t NUM_INPUTS = 2;
	static const uint16_t INPUT_SIZE = 2;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL1712_t() {
		str = "EL1712";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
};

struct EL1722_t FINAL : terminal_t {
	static const uint32_t ID = 1722;
	static const uint16_t NUM_INPUTS = 2;
	static const uint16_t INPUT_SIZE = 2;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL1722_t() {
		str = "EL1722";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
};

struct EL1804_t FINAL : terminal_t {
	static const uint32_t ID = 1804;
	static const uint16_t NUM_INPUTS = 4;
	static const uint16_t INPUT_SIZE = 4;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL1804_t() {
		str = "EL1804";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
};

struct EL1808_t FINAL : terminal_t {
	static const uint32_t ID = 1808;
	static const uint16_t NUM_INPUTS = 8;
	static const uint16_t INPUT_SIZE = 8;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL1808_t() {
		str = "EL1808";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
};

struct EL1809_t FINAL : terminal_t {
	static const uint32_t ID = 1809;
	static const uint16_t NUM_INPUTS = 16;
	static const uint16_t INPUT_SIZE = 16;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL1809_t() {
		str = "EL1809";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
};

struct EL1814_t FINAL : terminal_t {
	static const uint32_t ID = 1814;
	static const uint16_t NUM_INPUTS = 4;
	static const uint16_t INPUT_SIZE = 4;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL1814_t() {
		str = "EL1814";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
};

struct EL1819_t FINAL : terminal_t {
	static const uint32_t ID = 1819;
	static const uint16_t NUM_INPUTS = 16;
	static const uint16_t INPUT_SIZE = 16;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL1819_t() {
		str = "EL1819";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
};

struct EL2001_t FINAL : terminal_t {
	static const uint32_t ID = 2001;
	static const uint16_t NUM_INPUTS = 0;
	static const uint16_t INPUT_SIZE = 0;
	static const uint16_t NUM_OUTPUTS = 1;
	static const uint16_t OUTPUT_SIZE = 1;
	EL2001_t() {
		str = "EL2001";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
};

struct EL2002_t FINAL : terminal_t {
	static const uint32_t ID = 2002;
	static const uint16_t NUM_INPUTS = 0;
	static const uint16_t INPUT_SIZE = 0;
	static const uint16_t NUM_OUTPUTS = 2;
	static const uint16_t OUTPUT_SIZE = 2;
	EL2002_t() {
		str = "EL2002";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
};

struct EL2004_t FINAL : terminal_t {
	static const uint32_t ID = 2004;
	static const uint16_t NUM_INPUTS = 0;
	static const uint16_t INPUT_SIZE = 0;
	static const uint16_t NUM_OUTPUTS = 4;
	static const uint16_t OUTPUT_SIZE = 4;
	EL2004_t() {
		str = "EL2004";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
};

struct EL2008_t FINAL : terminal_t {
	static const uint32_t ID = 2008;
	static const uint16_t NUM_INPUTS = 0;
	static const uint16_t INPUT_SIZE = 0;
	static const uint16_t NUM_OUTPUTS = 8;
	static const uint16_t OUTPUT_SIZE = 8;
	EL2008_t() {
		str = "EL2008";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
};

struct EL2022_t FINAL : terminal_t {
	static const uint32_t ID = 2022;
	static const uint16_t NUM_INPUTS = 0;
	static const uint16_t INPUT_SIZE = 0;
	static const uint16_t NUM_OUTPUTS = 2;
	static const uint16_t OUTPUT_SIZE = 2;
	EL2022_t() {
		str = "EL2022";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
};

struct EL2024_t FINAL : terminal_t {
	static const uint32_t ID = 2024;
	static const uint16_t NUM_INPUTS = 0;
	static const uint16_t INPUT_SIZE = 0;
	static const uint16_t NUM_OUTPUTS = 4;
	static const uint16_t OUTPUT_SIZE = 4;
	EL2024_t() {
		str = "EL2024";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
};

struct EL2042_t FINAL : terminal_t {
	static const uint32_t ID = 2042;
	static const uint16_t NUM_INPUTS = 0;
	static const uint16_t INPUT_SIZE = 0;
	static const uint16_t NUM_OUTPUTS = 2;
	static const uint16_t OUTPUT_SIZE = 2;
	EL2042_t() {
		str = "EL2042";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
};

struct EL2084_t FINAL : terminal_t {
	static const uint32_t ID = 2084;
	static const uint16_t NUM_INPUTS = 0;
	static const uint16_t INPUT_SIZE = 0;
	static const uint16_t NUM_OUTPUTS = 4;
	static const uint16_t OUTPUT_SIZE = 4;
	EL2084_t() {
		str = "EL2084";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
};

struct EL2088_t FINAL : terminal_t {
	static const uint32_t ID = 2088;
	static const uint16_t NUM_INPUTS = 0;
	static const uint16_t INPUT_SIZE = 0;
	static const uint16_t NUM_OUTPUTS = 8;
	static const uint16_t OUTPUT_SIZE = 8;
	EL2088_t() {
		str = "EL2088";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
};

struct EL2124_t FINAL : terminal_t {
	static const uint32_t ID = 2124;
	static const uint16_t NUM_INPUTS = 0;
	static const uint16_t INPUT_SIZE = 0;
	static const uint16_t NUM_OUTPUTS = 4;
	static const uint16_t OUTPUT_SIZE = 4;
	EL2124_t() {
		str = "EL2124";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
};

struct EL2794_t FINAL : terminal_t {
	static const uint32_t ID = 2794;
	static const uint16_t NUM_INPUTS = 0;
	static const uint16_t INPUT_SIZE = 0;
	static const uint16_t NUM_OUTPUTS = 4;
	static const uint16_t OUTPUT_SIZE = 4;
	EL2794_t() {
		str = "EL2794";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
};

struct EL2808_t FINAL : terminal_t {
	static const uint32_t ID = 2808;
	static const uint16_t NUM_INPUTS = 0;
	static const uint16_t INPUT_SIZE = 0;
	static const uint16_t NUM_OUTPUTS = 8;
	static const uint16_t OUTPUT_SIZE = 8;
	EL2808_t() {
		str = "EL2808";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
};

struct EL2816_t FINAL : terminal_t {
	static const uint32_t ID = 2816;
	static const uint16_t NUM_INPUTS = 0;
	static const uint16_t INPUT_SIZE = 0;
	static const uint16_t NUM_OUTPUTS = 16;
	static const uint16_t OUTPUT_SIZE = 16;
	EL2816_t() {
		str = "EL2816";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
};

struct EL3001_t FINAL : terminal_t {
	static const uint32_t ID = 3001;
	static const uint16_t NUM_INPUTS = 1;
	static const uint16_t INPUT_SIZE = 2;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL3001_t() {
		str = "EL3001";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL3002_t FINAL : terminal_t {
	static const uint32_t ID = 3002;
	static const uint16_t NUM_INPUTS = 2;
	static const uint16_t INPUT_SIZE = 4;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL3002_t() {
		str = "EL3002";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL3004_t FINAL : terminal_t {
	static const uint32_t ID = 3004;
	static const uint16_t NUM_INPUTS = 4;
	static const uint16_t INPUT_SIZE = 8;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL3004_t() {
		str = "EL3004";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL3008_t FINAL : terminal_t {
	static const uint32_t ID = 3008;
	static const uint16_t NUM_INPUTS = 8;
	static const uint16_t INPUT_SIZE = 16;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL3008_t() {
		str = "EL3008";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL3012_t FINAL : terminal_t {
	static const uint32_t ID = 3012;
	static const uint16_t NUM_INPUTS = 2;
	static const uint16_t INPUT_SIZE = 4;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL3012_t() {
		str = "EL3012";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL3014_t FINAL : terminal_t {
	static const uint32_t ID = 3014;
	static const uint16_t NUM_INPUTS = 4;
	static const uint16_t INPUT_SIZE = 8;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL3014_t() {
		str = "EL3014";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL3021_t FINAL : terminal_t {
	static const uint32_t ID = 3021;
	static const uint16_t NUM_INPUTS = 1;
	static const uint16_t INPUT_SIZE = 2;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL3021_t() {
		str = "EL3021";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL3022_t FINAL : terminal_t {
	static const uint32_t ID = 3022;
	static const uint16_t NUM_INPUTS = 2;
	static const uint16_t INPUT_SIZE = 4;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL3022_t() {
		str = "EL3022";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL3024_t FINAL : terminal_t {
	static const uint32_t ID = 3024;
	static const uint16_t NUM_INPUTS = 4;
	static const uint16_t INPUT_SIZE = 8;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL3024_t() {
		str = "EL3024";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL3041_t FINAL : terminal_t {
	static const uint32_t ID = 3041;
	static const uint16_t NUM_INPUTS = 1;
	static const uint16_t INPUT_SIZE = 2;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL3041_t() {
		str = "EL3041";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL3042_t FINAL : terminal_t {
	static const uint32_t ID = 3042;
	static const uint16_t NUM_INPUTS = 2;
	static const uint16_t INPUT_SIZE = 4;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL3042_t() {
		str = "EL3042";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL3044_t FINAL : terminal_t {
	static const uint32_t ID = 3044;
	static const uint16_t NUM_INPUTS = 4;
	static const uint16_t INPUT_SIZE = 8;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL3044_t() {
		str = "EL3044";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL3048_t FINAL : terminal_t {
	static const uint32_t ID = 3048;
	static const uint16_t NUM_INPUTS = 8;
	static const uint16_t INPUT_SIZE = 16;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL3048_t() {
		str = "EL3048";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL3051_t FINAL : terminal_t {
	static const uint32_t ID = 3051;
	static const uint16_t NUM_INPUTS = 1;
	static const uint16_t INPUT_SIZE = 2;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL3051_t() {
		str = "EL3051";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL3052_t FINAL : terminal_t {
	static const uint32_t ID = 3052;
	static const uint16_t NUM_INPUTS = 2;
	static const uint16_t INPUT_SIZE = 4;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL3052_t() {
		str = "EL3052";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL3054_t FINAL : terminal_t {
	static const uint32_t ID = 3054;
	static const uint16_t NUM_INPUTS = 4;
	static const uint16_t INPUT_SIZE = 8;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL3054_t() {
		str = "EL3054";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL3058_t FINAL : terminal_t {
	static const uint32_t ID = 3058;
	static const uint16_t NUM_INPUTS = 8;
	static const uint16_t INPUT_SIZE = 16;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL3058_t() {
		str = "EL3058";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL3061_t FINAL : terminal_t {
	static const uint32_t ID = 3061;
	static const uint16_t NUM_INPUTS = 1;
	static const uint16_t INPUT_SIZE = 2;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL3061_t() {
		str = "EL3061";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL3062_t FINAL : terminal_t {
	static const uint32_t ID = 3062;
	static const uint16_t NUM_INPUTS = 2;
	static const uint16_t INPUT_SIZE = 4;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL3062_t() {
		str = "EL3062";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL3064_t FINAL : terminal_t {
	static const uint32_t ID = 3064;
	static const uint16_t NUM_INPUTS = 4;
	static const uint16_t INPUT_SIZE = 8;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL3064_t() {
		str = "EL3064";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL3068_t FINAL : terminal_t {
	static const uint32_t ID = 3068;
	static const uint16_t NUM_INPUTS = 8;
	static const uint16_t INPUT_SIZE = 16;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL3068_t() {
		str = "EL3068";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL3101_t FINAL : terminal_t {
	static const uint32_t ID = 3101;
	static const uint16_t NUM_INPUTS = 1;
	static const uint16_t INPUT_SIZE = 2;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL3101_t() {
		str = "EL3101";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL3102_t FINAL : terminal_t {
	static const uint32_t ID = 3102;
	static const uint16_t NUM_INPUTS = 2;
	static const uint16_t INPUT_SIZE = 4;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL3102_t() {
		str = "EL3102";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL3104_t FINAL : terminal_t {
	static const uint32_t ID = 3104;
	static const uint16_t NUM_INPUTS = 4;
	static const uint16_t INPUT_SIZE = 8;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL3104_t() {
		str = "EL3104";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL3111_t FINAL : terminal_t {
	static const uint32_t ID = 3111;
	static const uint16_t NUM_INPUTS = 1;
	static const uint16_t INPUT_SIZE = 2;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL3111_t() {
		str = "EL3111";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL3112_t FINAL : terminal_t {
	static const uint32_t ID = 3112;
	static const uint16_t NUM_INPUTS = 2;
	static const uint16_t INPUT_SIZE = 4;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL3112_t() {
		str = "EL3112";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL3114_t FINAL : terminal_t {
	static const uint32_t ID = 3114;
	static const uint16_t NUM_INPUTS = 4;
	static const uint16_t INPUT_SIZE = 8;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL3114_t() {
		str = "EL3114";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL3121_t FINAL : terminal_t {
	static const uint32_t ID = 3121;
	static const uint16_t NUM_INPUTS = 1;
	static const uint16_t INPUT_SIZE = 2;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL3121_t() {
		str = "EL3121";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL3122_t FINAL : terminal_t {
	static const uint32_t ID = 3122;
	static const uint16_t NUM_INPUTS = 2;
	static const uint16_t INPUT_SIZE = 4;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL3122_t() {
		str = "EL3122";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL3124_t FINAL : terminal_t {
	static const uint32_t ID = 3124;
	static const uint16_t NUM_INPUTS = 4;
	static const uint16_t INPUT_SIZE = 8;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL3124_t() {
		str = "EL3124";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL3141_t FINAL : terminal_t {
	static const uint32_t ID = 3141;
	static const uint16_t NUM_INPUTS = 1;
	static const uint16_t INPUT_SIZE = 2;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL3141_t() {
		str = "EL3141";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL3142_t FINAL : terminal_t {
	static const uint32_t ID = 3142;
	static const uint16_t NUM_INPUTS = 2;
	static const uint16_t INPUT_SIZE = 4;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL3142_t() {
		str = "EL3142";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL3144_t FINAL : terminal_t {
	static const uint32_t ID = 3144;
	static const uint16_t NUM_INPUTS = 4;
	static const uint16_t INPUT_SIZE = 8;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL3144_t() {
		str = "EL3144";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL3151_t FINAL : terminal_t {
	static const uint32_t ID = 3151;
	static const uint16_t NUM_INPUTS = 1;
	static const uint16_t INPUT_SIZE = 2;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL3151_t() {
		str = "EL3151";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL3152_t FINAL : terminal_t {
	static const uint32_t ID = 3152;
	static const uint16_t NUM_INPUTS = 2;
	static const uint16_t INPUT_SIZE = 4;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL3152_t() {
		str = "EL3152";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL3154_t FINAL : terminal_t {
	static const uint32_t ID = 3154;
	static const uint16_t NUM_INPUTS = 4;
	static const uint16_t INPUT_SIZE = 8;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL3154_t() {
		str = "EL3154";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL3161_t FINAL : terminal_t {
	static const uint32_t ID = 3161;
	static const uint16_t NUM_INPUTS = 1;
	static const uint16_t INPUT_SIZE = 2;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL3161_t() {
		str = "EL3161";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL3162_t FINAL : terminal_t {
	static const uint32_t ID = 3162;
	static const uint16_t NUM_INPUTS = 2;
	static const uint16_t INPUT_SIZE = 4;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL3162_t() {
		str = "EL3162";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL3164_t FINAL : terminal_t {
	static const uint32_t ID = 3164;
	static const uint16_t NUM_INPUTS = 4;
	static const uint16_t INPUT_SIZE = 8;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL3164_t() {
		str = "EL3164";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL3174_t FINAL : terminal_t {
	static const uint32_t ID = 3174;
	static const uint16_t NUM_INPUTS = 4;
	static const uint16_t INPUT_SIZE = 8;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL3174_t() {
		str = "EL3174";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL3202_t FINAL : terminal_t {
	static const uint32_t ID = 3202;
	static const uint16_t NUM_INPUTS = 2;
	static const uint16_t INPUT_SIZE = 4;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL3202_t() {
		str = "EL3202";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL3314_t FINAL : terminal_t {
	static const uint32_t ID = 3314;
	static const uint16_t NUM_INPUTS = 4;
	static const uint16_t INPUT_SIZE = 8;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL3314_t() {
		str = "EL3314";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL3312_t FINAL : terminal_t {
	static const uint32_t ID = 3312;
	static const uint16_t NUM_INPUTS = 2;
	static const uint16_t INPUT_SIZE = 4;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL3312_t() {
		str = "EL3312";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL3311_t FINAL : terminal_t {
	static const uint32_t ID = 3311;
	static const uint16_t NUM_INPUTS = 1;
	static const uint16_t INPUT_SIZE = 2;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL3311_t() {
		str = "EL3311";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL3681_t FINAL : terminal_t {
	static const uint32_t ID = 3681;
	static const uint16_t NUM_INPUTS = 1;
	static const uint16_t INPUT_SIZE = 3;
	static const uint16_t NUM_OUTPUTS = 1;
	static const uint16_t OUTPUT_SIZE = 2;
	EL3681_t() {
		str = "EL3681";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
	static void _pdo_output_check();
};

struct EL4001_t FINAL : terminal_t {
	static const uint32_t ID = 4001;
	static const uint16_t NUM_INPUTS = 0;
	static const uint16_t INPUT_SIZE = 0;
	static const uint16_t NUM_OUTPUTS = 1;
	static const uint16_t OUTPUT_SIZE = 1;
	EL4001_t() {
		str = "EL4001";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_output_check();
};

struct EL4002_t FINAL : terminal_t {
	static const uint32_t ID = 4002;
	static const uint16_t NUM_INPUTS = 0;
	static const uint16_t INPUT_SIZE = 0;
	static const uint16_t NUM_OUTPUTS = 2;
	static const uint16_t OUTPUT_SIZE = 2;
	EL4002_t() {
		str = "EL4002";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_output_check();
};

struct EL4004_t FINAL : terminal_t {
	static const uint32_t ID = 4004;
	static const uint16_t NUM_INPUTS = 0;
	static const uint16_t INPUT_SIZE = 0;
	static const uint16_t NUM_OUTPUTS = 4;
	static const uint16_t OUTPUT_SIZE = 4;
	EL4004_t() {
		str = "EL4004";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_output_check();
};

struct EL4008_t FINAL : terminal_t {
	static const uint32_t ID = 4008;
	static const uint16_t NUM_INPUTS = 0;
	static const uint16_t INPUT_SIZE = 0;
	static const uint16_t NUM_OUTPUTS = 8;
	static const uint16_t OUTPUT_SIZE = 8;
	EL4008_t() {
		str = "EL4008";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_output_check();
};

struct EL4011_t FINAL : terminal_t {
	static const uint32_t ID = 4011;
	static const uint16_t NUM_INPUTS = 0;
	static const uint16_t INPUT_SIZE = 0;
	static const uint16_t NUM_OUTPUTS = 1;
	static const uint16_t OUTPUT_SIZE = 1;
	EL4011_t() {
		str = "EL4011";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_output_check();
};

struct EL4012_t FINAL : terminal_t {
	static const uint32_t ID = 4012;
	static const uint16_t NUM_INPUTS = 0;
	static const uint16_t INPUT_SIZE = 0;
	static const uint16_t NUM_OUTPUTS = 2;
	static const uint16_t OUTPUT_SIZE = 2;
	EL4012_t() {
		str = "EL4012";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_output_check();
};

struct EL4014_t FINAL : terminal_t {
	static const uint32_t ID = 4014;
	static const uint16_t NUM_INPUTS = 0;
	static const uint16_t INPUT_SIZE = 0;
	static const uint16_t NUM_OUTPUTS = 4;
	static const uint16_t OUTPUT_SIZE = 4;
	EL4014_t() {
		str = "EL4014";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_output_check();
};

struct EL4018_t FINAL : terminal_t {
	static const uint32_t ID = 4018;
	static const uint16_t NUM_INPUTS = 0;
	static const uint16_t INPUT_SIZE = 0;
	static const uint16_t NUM_OUTPUTS = 8;
	static const uint16_t OUTPUT_SIZE = 8;
	EL4018_t() {
		str = "EL4018";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_output_check();
};

struct EL4021_t FINAL : terminal_t {
	static const uint32_t ID = 4021;
	static const uint16_t NUM_INPUTS = 0;
	static const uint16_t INPUT_SIZE = 0;
	static const uint16_t NUM_OUTPUTS = 1;
	static const uint16_t OUTPUT_SIZE = 1;
	EL4021_t() {
		str = "EL4021";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_output_check();
};

struct EL4022_t FINAL : terminal_t {
	static const uint32_t ID = 4022;
	static const uint16_t NUM_INPUTS = 0;
	static const uint16_t INPUT_SIZE = 0;
	static const uint16_t NUM_OUTPUTS = 2;
	static const uint16_t OUTPUT_SIZE = 2;
	EL4022_t() {
		str = "EL4022";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_output_check();
};

struct EL4024_t FINAL : terminal_t {
	static const uint32_t ID = 4024;
	static const uint16_t NUM_INPUTS = 0;
	static const uint16_t INPUT_SIZE = 0;
	static const uint16_t NUM_OUTPUTS = 4;
	static const uint16_t OUTPUT_SIZE = 4;
	EL4024_t() {
		str = "EL4024";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_output_check();
};

struct EL4028_t FINAL : terminal_t {
	static const uint32_t ID = 4028;
	static const uint16_t NUM_INPUTS = 0;
	static const uint16_t INPUT_SIZE = 0;
	static const uint16_t NUM_OUTPUTS = 8;
	static const uint16_t OUTPUT_SIZE = 8;
	EL4028_t() {
		str = "EL4028";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_output_check();
};

struct EL4031_t FINAL : terminal_t {
	static const uint32_t ID = 4031;
	static const uint16_t NUM_INPUTS = 0;
	static const uint16_t INPUT_SIZE = 0;
	static const uint16_t NUM_OUTPUTS = 1;
	static const uint16_t OUTPUT_SIZE = 1;
	EL4031_t() {
		str = "EL4031";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_output_check();
};

struct EL4032_t FINAL : terminal_t {
	static const uint32_t ID = 4032;
	static const uint16_t NUM_INPUTS = 0;
	static const uint16_t INPUT_SIZE = 0;
	static const uint16_t NUM_OUTPUTS = 2;
	static const uint16_t OUTPUT_SIZE = 2;
	EL4032_t() {
		str = "EL4032";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_output_check();
};

struct EL4034_t FINAL : terminal_t {
	static const uint32_t ID = 4034;
	static const uint16_t NUM_INPUTS = 0;
	static const uint16_t INPUT_SIZE = 0;
	static const uint16_t NUM_OUTPUTS = 4;
	static const uint16_t OUTPUT_SIZE = 4;
	EL4034_t() {
		str = "EL4034";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_output_check();
};

struct EL4038_t FINAL : terminal_t {
	static const uint32_t ID = 4038;
	static const uint16_t NUM_INPUTS = 0;
	static const uint16_t INPUT_SIZE = 0;
	static const uint16_t NUM_OUTPUTS = 8;
	static const uint16_t OUTPUT_SIZE = 8;
	EL4038_t() {
		str = "EL4038";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_output_check();
};

struct EL4102_t FINAL : terminal_t {
	static const uint32_t ID = 4102;
	static const uint16_t NUM_INPUTS = 0;
	static const uint16_t INPUT_SIZE = 0;
	static const uint16_t NUM_OUTPUTS = 2;
	static const uint16_t OUTPUT_SIZE = 2;
	EL4102_t() {
		str = "EL4102";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_output_check();
};

struct EL4104_t FINAL : terminal_t {
	static const uint32_t ID = 4104;
	static const uint16_t NUM_INPUTS = 0;
	static const uint16_t INPUT_SIZE = 0;
	static const uint16_t NUM_OUTPUTS = 4;
	static const uint16_t OUTPUT_SIZE = 4;
	EL4104_t() {
		str = "EL4104";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_output_check();
};

struct EL4114_t FINAL : terminal_t {
	static const uint32_t ID = 4114;
	static const uint16_t NUM_INPUTS = 0;
	static const uint16_t INPUT_SIZE = 0;
	static const uint16_t NUM_OUTPUTS = 4;
	static const uint16_t OUTPUT_SIZE = 4;
	EL4114_t() {
		str = "EL4114";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_output_check();
};

struct EL4112_t FINAL : terminal_t {
	static const uint32_t ID = 4112;
	static const uint16_t NUM_INPUTS = 0;
	static const uint16_t INPUT_SIZE = 0;
	static const uint16_t NUM_OUTPUTS = 2;
	static const uint16_t OUTPUT_SIZE = 2;
	EL4112_t() {
		str = "EL4112";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_output_check();
};

struct EL4134_t FINAL : terminal_t {
	static const uint32_t ID = 4134;
	static const uint16_t NUM_INPUTS = 0;
	static const uint16_t INPUT_SIZE = 0;
	static const uint16_t NUM_OUTPUTS = 4;
	static const uint16_t OUTPUT_SIZE = 4;
	EL4134_t() {
		str = "EL4134";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_output_check();
};

struct EL4132_t FINAL : terminal_t {
	static const uint32_t ID = 4132;
	static const uint16_t NUM_INPUTS = 0;
	static const uint16_t INPUT_SIZE = 0;
	static const uint16_t NUM_OUTPUTS = 2;
	static const uint16_t OUTPUT_SIZE = 2;
	EL4132_t() {
		str = "EL4132";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_output_check();
};

struct EL4122_t FINAL : terminal_t {
	static const uint32_t ID = 4122;
	static const uint16_t NUM_INPUTS = 0;
	static const uint16_t INPUT_SIZE = 0;
	static const uint16_t NUM_OUTPUTS = 2;
	static const uint16_t OUTPUT_SIZE = 2;
	EL4122_t() {
		str = "EL4122";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_output_check();
};

struct EL5042_t FINAL : terminal_t {
	static const uint32_t ID = 5042;
	static const uint16_t NUM_INPUTS = 2;
	static const uint16_t INPUT_SIZE = 6;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 0;
	EL5042_t() {
		str = "EL5042";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
};

struct EL7047_t FINAL : terminal_t {
	static const uint32_t ID = 7047;
	static const uint16_t NUM_INPUTS = 0;
	static const uint16_t INPUT_SIZE = 14;
	static const uint16_t NUM_OUTPUTS = 0;
	static const uint16_t OUTPUT_SIZE = 14;
	EL7047_t() {
		str = "EL7047";
		id = ID;
		numInputs = NUM_INPUTS;
		numOutputs = NUM_OUTPUTS;
		inputSize = INPUT_SIZE;
		outputSize = OUTPUT_SIZE;
	}
	static void _pdo_input_check();
	static void _pdo_output_check();
};

static const terminal_t s_terminalInfos[] = {
	EL1001_t(), EL1002_t(), EL1004_t(), EL1008_t(), EL1012_t(), EL1014_t(), EL1018_t(), EL1024_t(), EL1034_t(),
	EL1084_t(), EL1088_t(), EL1094_t(), EL1098_t(), EL1104_t(), EL1114_t(), EL1124_t(), EL1134_t(), EL1144_t(),
	EL1184_t(), EL1202_t(), EL1382_t(), EL1702_t(), EL1712_t(), EL1722_t(), EL1804_t(), EL1808_t(), EL1809_t(),
	EL1814_t(), EL1819_t(), EL2001_t(), EL2002_t(), EL2004_t(), EL2008_t(), EL2022_t(), EL2024_t(), EL2042_t(),
	EL2084_t(), EL2088_t(), EL2124_t(), EL2794_t(), EL2808_t(), EL2816_t(), EL3001_t(), EL3002_t(), EL3004_t(),
	EL3008_t(), EL3012_t(), EL3014_t(), EL3021_t(), EL3022_t(), EL3024_t(), EL3041_t(), EL3042_t(), EL3044_t(),
	EL3048_t(), EL3051_t(), EL3052_t(), EL3054_t(), EL3058_t(), EL3061_t(), EL3062_t(), EL3064_t(), EL3068_t(),
	EL3101_t(), EL3102_t(), EL3104_t(), EL3111_t(), EL3112_t(), EL3114_t(), EL3121_t(), EL3122_t(), EL3124_t(),
	EL3141_t(), EL3142_t(), EL3144_t(), EL3151_t(), EL3152_t(), EL3154_t(), EL3161_t(), EL3162_t(), EL3164_t(),
	EL3174_t(), EL3202_t(), EL3314_t(), EL3312_t(), EL3311_t(), EL3681_t(), EL4001_t(), EL4002_t(), EL4004_t(),
	EL4008_t(), EL4011_t(), EL4012_t(), EL4014_t(), EL4018_t(), EL4021_t(), EL4022_t(), EL4024_t(), EL4028_t(),
	EL4031_t(), EL4032_t(), EL4034_t(), EL4038_t(), EL4102_t(), EL4104_t(), EL4114_t(), EL4112_t(), EL4134_t(),
	EL4132_t(), EL4122_t(), EL5042_t(), EL7047_t(),
};

MAYBE_UNUSED static void __pdo_check() {
	EL3001_t::_pdo_input_check();
	EL3002_t::_pdo_input_check();
	EL3004_t::_pdo_input_check();
	EL3008_t::_pdo_input_check();
	EL3012_t::_pdo_input_check();
	EL3014_t::_pdo_input_check();
	EL3021_t::_pdo_input_check();
	EL3022_t::_pdo_input_check();
	EL3024_t::_pdo_input_check();
	EL3041_t::_pdo_input_check();
	EL3042_t::_pdo_input_check();
	EL3044_t::_pdo_input_check();
	EL3048_t::_pdo_input_check();
	EL3051_t::_pdo_input_check();
	EL3052_t::_pdo_input_check();
	EL3054_t::_pdo_input_check();
	EL3058_t::_pdo_input_check();
	EL3061_t::_pdo_input_check();
	EL3062_t::_pdo_input_check();
	EL3064_t::_pdo_input_check();
	EL3068_t::_pdo_input_check();
	EL3101_t::_pdo_input_check();
	EL3102_t::_pdo_input_check();
	EL3104_t::_pdo_input_check();
	EL3111_t::_pdo_input_check();
	EL3112_t::_pdo_input_check();
	EL3114_t::_pdo_input_check();
	EL3121_t::_pdo_input_check();
	EL3122_t::_pdo_input_check();
	EL3124_t::_pdo_input_check();
	EL3141_t::_pdo_input_check();
	EL3142_t::_pdo_input_check();
	EL3144_t::_pdo_input_check();
	EL3151_t::_pdo_input_check();
	EL3152_t::_pdo_input_check();
	EL3154_t::_pdo_input_check();
	EL3161_t::_pdo_input_check();
	EL3162_t::_pdo_input_check();
	EL3164_t::_pdo_input_check();
	EL3174_t::_pdo_input_check();
	EL3202_t::_pdo_input_check();
	EL3314_t::_pdo_input_check();
	EL3312_t::_pdo_input_check();
	EL3311_t::_pdo_input_check();
	EL3681_t::_pdo_input_check();
	EL3681_t::_pdo_output_check();
	EL4001_t::_pdo_output_check();
	EL4002_t::_pdo_output_check();
	EL4004_t::_pdo_output_check();
	EL4008_t::_pdo_output_check();
	EL4011_t::_pdo_output_check();
	EL4012_t::_pdo_output_check();
	EL4014_t::_pdo_output_check();
	EL4018_t::_pdo_output_check();
	EL4021_t::_pdo_output_check();
	EL4022_t::_pdo_output_check();
	EL4024_t::_pdo_output_check();
	EL4028_t::_pdo_output_check();
	EL4031_t::_pdo_output_check();
	EL4032_t::_pdo_output_check();
	EL4034_t::_pdo_output_check();
	EL4038_t::_pdo_output_check();
	EL4102_t::_pdo_output_check();
	EL4104_t::_pdo_output_check();
	EL4114_t::_pdo_output_check();
	EL4112_t::_pdo_output_check();
	EL4134_t::_pdo_output_check();
	EL4132_t::_pdo_output_check();
	EL4122_t::_pdo_output_check();
	EL5042_t::_pdo_input_check();
	EL7047_t::_pdo_input_check();
	EL7047_t::_pdo_output_check();
}
